### ISSUE TITLE
Downloading manifests unexepected error - 508 Infinite Loop

### ISSUE THREAD

**Issue by tpill90** [tpill90/steam-lancache-prefill#105]
```
[[2:26:17 PM]] An exception occurred while downloading manifests[[2:26:17 PM]] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 508 ().
   at SteamKit2.CDN.Client.DoRawCommandAsync(Server server, String command, Server proxyServer)
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte[] depotKey, Server proxyServer)
```

Reported by @kiza56

**Comment by tpill90** [comment]
[SteamPrefill-1.3.4-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9463161/SteamPrefill-1.3.4-linux-x64.zip)
[SteamPrefill-1.3.4-osx-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9463162/SteamPrefill-1.3.4-osx-x64.zip)
[SteamPrefill-1.3.4-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9463163/SteamPrefill-1.3.4-win-x64.zip)
[SteamPrefill-1.3.4-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9463164/SteamPrefill-1.3.4-linux-arm64.zip)

**Comment by wzqvip** [comment]
I still encounter this problem. I can access steamcommunity website, use steam client to download games. When I run this on windows, i still get 


```


[7:55:03 PM] Starting The Long Dark
[7:55:06 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.
Retrying...depot manifests...
[7:55:07 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.
Retrying...depot manifests...
[7:55:09 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.
Retrying...depot manifests...
[7:55:10 PM] Unexpected download error : Unable to download manifests!  Skipping app...

[7:55:10 PM] Starting Titanfall? 2
[7:55:14 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.
Retrying...depot manifests...
[7:55:15 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.
Retrying...depot manifests...
[7:55:16 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.
Retrying...depot manifests...
[7:55:18 PM] Unexpected download error : Unable to download manifests!  Skipping app...

[7:55:18 PM] Prefill complete!
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────  Prefilled 12 apps totaling 0 b in 01:35.38

   Updated │ Up To Date │ Failed
  ─────────┼────────────┼────────
      0    │     0      │   12

[7:55:18 PM] Disconnected from Steam!

```

**Comment by tpill90** [comment]
Could you add your app.log file here so that I can look at it?

**Comment by tpill90** [comment]
Closing this again since there has been no additional info.

**Comment by wzqvip** [comment]
> Could you add your app.log file here so that I can look at it?

```
[11:47:11 AM] Starting login!
[11:47:18 AM] Starting login!
[11:47:26 AM] Connecting with CellId: 0
[11:47:28 AM] Connected to Steam!
[11:47:28 AM] Requesting new access token...
[11:47:37 AM] Logged into Steam
[11:47:37 AM] Connected to CM Unspecified/ext3-fra1.steamserver.net:27024
[11:47:39 AM] Loaded account licenses                                 01.1449
[11:47:39 AM] Steam session initialization complete!                  21.1612
[11:47:43 AM] Loaded metadata for 1511 apps                           04.3749
[11:47:56 AM] Selected 2 apps to prefill!  
[11:47:57 AM] Loaded metadata for 0 apps                              00.0001
[11:47:57 AM] Loaded metadata for 0 apps                              00.0001
[11:47:57 AM] Starting Aperture Desk Job
[11:47:57 AM] Requesting available CDNs. Pool currently has 0 servers available, below the desired count of 5
[11:48:01 AM] Downloading manifests for 2 depots
[11:48:01 AM] Downloading manifest 8072925914291252462 for depot 1902491
[11:48:01 AM] Using CDN st.dl.eccdnx.com
[11:48:02 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[11:48:02 AM] An exception occurred while downloading manifests
[11:48:02 AM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer, String cdnAuthToken)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:48:02 AM] Downloading manifest 8072925914291252462 for depot 1902491
[11:48:03 AM] Using CDN dl.steam.clngaa.com
[11:48:03 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[11:48:03 AM] An exception occurred while downloading manifests
[11:48:03 AM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer, String cdnAuthToken)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:48:04 AM] Downloading manifest 8072925914291252462 for depot 1902491
[11:48:04 AM] Using CDN xz.pphimalayanrt.com
[11:48:05 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[11:48:05 AM] An exception occurred while downloading manifests
[11:48:05 AM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer, String cdnAuthToken)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:48:06 AM] Unexpected download error : Unable to download manifests!  Skipping app...
[11:48:06 AM] SteamPrefill.Models.Exceptions.ManifestException: Unable to download manifests!
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
   at SteamPrefill.Handlers.DepotHandler.BuildChunkDownloadQueueAsync(List`1 depots)
   at SteamPrefill.SteamManager.<>c__DisplayClass13_0.<<DownloadSingleAppAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync(Func`2 action) in Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync(String status, Func`2 func) in Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.SteamManager.DownloadSingleAppAsync(UInt32 appId)
   at SteamPrefill.SteamManager.DownloadMultipleAppsAsync(Boolean downloadAllOwnedGames, Boolean prefillRecentGames, Nullable`1 prefillPopularGames)
[11:48:06 AM] Starting Apex Legends
[11:48:06 AM] Requesting available CDNs. Pool currently has 0 servers available, below the desired count of 5
[11:50:48 AM] Starting login!
[11:50:48 AM] Connecting with CellId: 46
[11:50:50 AM] Connected to Steam!
[11:50:50 AM] Logged into Steam
[11:50:50 AM] Connected to CM Unspecified/ext7-hkg1.steamserver.net:27032
[11:50:51 AM] Loaded account licenses                                 00.4281
[11:50:51 AM] Steam session initialization complete!                  02.6330
[11:50:51 AM] Building benchmark workload file...
[11:50:51 AM] Loaded metadata for 2 apps                              00.5636
[11:50:52 AM] Loaded metadata for 1 apps                              00.5938
[11:50:52 AM] Requesting available CDNs. Pool currently has 0 servers available, below the desired count of 5
[11:50:55 AM] Downloading manifests for 2 depots
[11:50:55 AM] Downloading manifests for 1 depots
[11:50:55 AM] Downloading manifest 5522521261566906225 for depot 1172471
[11:50:55 AM] Downloading manifest 8072925914291252462 for depot 1902491
[11:50:55 AM] Using CDN dl.steam.clngaa.com
[11:50:55 AM] Using CDN xz.pphimalayanrt.com
[11:50:55 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[11:50:55 AM] An exception occurred while downloading manifests
[11:50:55 AM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer, String cdnAuthToken)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:50:55 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[11:50:55 AM] An exception occurred while downloading manifests
[11:50:55 AM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer, String cdnAuthToken)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:50:55 AM] Downloading manifest 8072925914291252462 for depot 1902491
[11:50:55 AM] Downloading manifest 5522521261566906225 for depot 1172471
[11:50:56 AM] Using CDN st.dl.eccdnx.com
[11:50:56 AM]    An unexpected error (SteamPrefill.Models.Exceptions.CdnExhaustionException) occurred while downloading manifests.  Retrying...
[11:50:56 AM] An exception occurred while downloading manifests
[11:50:56 AM] SteamPrefill.Models.Exceptions.CdnExhaustionException: Available Steam CDN servers exhausted!  No more servers available to retry!  Try again in a few minutes
   at SteamPrefill.Handlers.Steam.CdnPool.TakeConnection()
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:50:56 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[11:50:56 AM] An exception occurred while downloading manifests
[11:50:56 AM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer, String cdnAuthToken)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:50:57 AM] Downloading manifest 5522521261566906225 for depot 1172471
[11:50:57 AM] Downloading manifest 8072925914291252462 for depot 1902491
[11:50:57 AM]    An unexpected error (SteamPrefill.Models.Exceptions.CdnExhaustionException) occurred while downloading manifests.  Retrying...
[11:50:57 AM] An exception occurred while downloading manifests
[11:50:57 AM] SteamPrefill.Models.Exceptions.CdnExhaustionException: Available Steam CDN servers exhausted!  No more servers available to retry!  Try again in a few minutes
   at SteamPrefill.Handlers.Steam.CdnPool.TakeConnection()
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:50:57 AM]    An unexpected error (SteamPrefill.Models.Exceptions.CdnExhaustionException) occurred while downloading manifests.  Retrying...
[11:50:57 AM] An exception occurred while downloading manifests
[11:50:57 AM] SteamPrefill.Models.Exceptions.CdnExhaustionException: Available Steam CDN servers exhausted!  No more servers available to retry!  Try again in a few minutes
   at SteamPrefill.Handlers.Steam.CdnPool.TakeConnection()
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[11:50:59 AM] Benchmark file not built!  All apps were unowned and could not be included!
[11:50:59 AM] Disconnected from Steam!

```



I tried again on Ubuntu 24 and Ubuntu 18. Lancache seems to work well with steam client(manual fill), but I still get the error message from prefill.
