### ISSUE TITLE
Exception while scrolling through pages of apps

### ISSUE THREAD

**Issue by dlrudie** [tpill90/steam-lancache-prefill#13]
When using page down to select an app it will throw an exception after the 12th page. It this to me in Windows and in Linux.

Output from Windows Terminal:
![image](https://user-images.githubusercontent.com/1780069/180052062-d9aebadf-2c79-4031-82be-c2201ce4805b.png)

Copy/pasted exception for clarity:

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at Spectre.Console.ExceptionFormatter.TryGetTupleName(ParameterInfo parameter, Type parameterType, String& tupleName) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Widgets\Exceptions\ExceptionFormatter.cs:314
  at Spectre.Console.ExceptionFormatter.GetParameterName(ParameterInfo parameter) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Widgets\Exceptions\ExceptionFormatter.cs:280
  at Spectre.Console.ExceptionFormatter.<>c__DisplayClass4_0.<AppendParameters>b__0(ParameterInfo x) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Widgets\Exceptions\ExceptionFormatter.cs:121
  at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
  at System.String.Join(String separator, IEnumerable`1 values)
  at Spectre.Console.ExceptionFormatter.AppendParameters(StringBuilder builder, MethodBase method, ExceptionSettings settings) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Widgets\Exceptions\ExceptionFormatter.cs:125
  at Spectre.Console.ExceptionFormatter.GetStackFrames(Exception ex, ExceptionSettings settings) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Widgets\Exceptions\ExceptionFormatter.cs:86
  at Spectre.Console.ExceptionFormatter.GetException(Exception exception, ExceptionSettings settings) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Widgets\Exceptions\ExceptionFormatter.cs:22
  at Spectre.Console.ExceptionFormatter.Format(Exception exception, ExceptionSettings settings) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Widgets\Exceptions\ExceptionFormatter.cs:7
  at Spectre.Console.ExceptionExtensions.GetRenderable(Exception exception, ExceptionSettings settings) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Extensions\ExceptionExtensions.cs:40
  at Spectre.Console.ExceptionExtensions.GetRenderable(Exception exception, ExceptionFormats format) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Extensions\ExceptionExtensions.cs:21
  at Spectre.Console.AnsiConsoleExtensions.WriteException(IAnsiConsole console, Exception exception, ExceptionFormats format) in C:\Users\Tim\Dropbox\Programming\dotnet-public\SteamPrefill\External\SpectreConsole\src\Spectre.Console\Extensions\AnsiConsoleExtensions.Exceptions.cs:16
  at SteamPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)
  at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:147
  at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in D:\a\CliFx\CliFx\CliFx\CliApplication.cs:191
```

**Comment by dlrudie** [comment]
It crashes after it hits a title called HOMEFRONT. Directly after HOMEFRONT is one titled HOMEFRONT [Alpha] with square brackets.

**Comment by tpill90** [comment]
Fix for this was merged in #17.

**Comment by tpill90** [comment]
[SteamPrefill-1.1.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9168317/SteamPrefill-1.1.0-linux-x64.zip)
[SteamPrefill-1.1.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9168318/SteamPrefill-1.1.0-win-x64.zip)

**Comment by tpill90** [comment]
[SteamPrefill-1.1.0-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9168675/SteamPrefill-1.1.0-win-x64.zip)
[SteamPrefill-1.1.0-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9168676/SteamPrefill-1.1.0-linux-x64.zip)
