### ISSUE TITLE
Windows Client - Prefill caching issues only on some games

### ISSUE THREAD

**Issue by raz3r83** [tpill90/steam-lancache-prefill#223]
Getting errors trying to use prefill to cache Left 4 Dead 2, PAYDAY 2, Warhammer 40,000: Darktide and a few other games, as per discussion on Discord.

raz3r83 — Today at 16:45
Left 4 Dead 2 again and a couple of others, was getting an error for Space Hulk: Deathwing - Enhanced Edition but a retry and thats now going through
Image
Error Log
[[3:25:52 AM]] An exception occurred while downloading manifests[[3:25:52 AM]] System.TimeoutException: The operation has timed out.
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[3:26:02 AM]] An exception occurred while downloading manifests[[3:26:02 AM]] System.TimeoutException: The operation has timed out.
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[3:26:13 AM]] An exception occurred while downloading manifests[[3:26:13 AM]] System.TimeoutException: The operation has timed out.
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
... (12 KB left)
Expand
[errorlog.txt](https://github.com/tpill90/steam-lancache-prefill/files/10043537/errorlog.txt)
errorlog.txt
62 KB
after its finished this run I will try it again with --no-cache
Awesome app BTW much appreciated for the effort
tpill90 — Today at 16:51
Don't do the no cache

Also I appreciate the feedback
Can you zip up your cache folder and send it over?
Preferably if you could throw it up on a github issue
I have a feeling @LilTrublMakr is on to something.  I'm guessing the cache got corrupted

[Cache.zip](https://github.com/tpill90/steam-lancache-prefill/files/10043524/Cache.zip)

**Comment by tpill90** [comment]
Released in [v1.8.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.8.0)
