### ISSUE TITLE
SteamPrefill 1.8.1 x64 Linux - Unable to download Manifest - VTOL VR

### ISSUE THREAD

**Issue by Shad0wGeneral** [tpill90/steam-lancache-prefill#229]
Get the following error when attempting a prefill and it gets to the game stated in the Title.

``[[5:09:21 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1770480 2836902461265788005
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)``

**Comment by tpill90** [comment]
SteamDB link of the affected app : https://steamdb.info/app/667970/depots/

**Comment by tpill90** [comment]
Released in [v1.9.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v1.9.0)

**Comment by LokiLeiche** [comment]
This should be closed again as discussed in #447 and the discord
