### ISSUE TITLE
Failed to save Steam session key.  Steam account will not stay logged in

### ISSUE THREAD

**Issue by DevURnd** [tpill90/steam-lancache-prefill#272]
Hi,

Trying to run a prefill and I get the following error:
```
$ ./SteamPrefill prefill --debug
[1:09:35 PM] Starting login!
A Steam account is required in order to prefill apps!
Please enter your Steam account name : 
Please enter your Steam password. (Password won't be saved) : ************
SteamKitDebug - ServerList: Resolving server list
SteamKitDebug - ServerList: Server list provider had no entries, will query SteamDirectory
SteamKitDebug - ServerList: Resolved 200 servers
SteamKitDebug - ServerList: Next server candidate: 162.254.196.67:27017 (Tcp)
SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/TcpConnection: Connecting to 162.254.196.67:27017...
SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/TcpConnection: Connected to 162.254.196.67:27017
SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/EnvelopeEncryptedConnection: Got encryption request. Universe: Public Protocol ver: 1
SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/EnvelopeEncryptedConnection: Encryption result: OK
2FA required for login.  Please enter your Steam Guard code from your authenticator app : SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/TcpConnection: Socket exception occurred while reading packet: System.IO.IOException: Connection lost while reading packet header.
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at System.IO.BinaryReader.ReadUInt32()
   at SteamKit2.TcpConnection.ReadPacket()
   --- End of inner exception stack trace ---
   at SteamKit2.TcpConnection.ReadPacket()
   at SteamKit2.TcpConnection.NetLoop()

SteamKitDebug - ServerList: Next server candidate: 162.254.196.84:27017 (Tcp)
SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/TcpConnection: Connecting to 162.254.196.84:27017...
SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/TcpConnection: Connected to 162.254.196.84:27017
SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/EnvelopeEncryptedConnection: Got encryption request. Universe: Public Protocol ver: 1
SteamKitDebug - 3ad58eb5483b441482209f12a1ae0e9e/EnvelopeEncryptedConnection: Encryption result: OK
[1:10:23 PM] Logged into Steam
[1:10:33 PM] Failed to save Steam session key.  Steam account will not stay logged in...
[1:10:33 PM] Steam session initialization complete!

[1:10:35 PM] Prefill complete!
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Prefilled 65 apps in 01:00.26

   Updated │ Up To Date
  ━━━━━━━━━┿━━━━━━━━━━━━
      0    │     65

[1:10:35 PM] Disconnected from Steam!
```

after that session finishes, trying again produces:
```
$ ./SteamPrefill prefill --debug
[1:28:57 PM] Starting login!
System.NullReferenceException: Object reference not set to an instance of an object.
  at async Task SteamPrefill.Handlers.Steam.Steam3Session.ConfigureLoginDetailsAsync()
  at async Task SteamPrefill.Handlers.Steam.Steam3Session.LoginToSteamAsync()
  at async Task SteamPrefill.SteamManager.InitializeAsync()
  at async ValueTask SteamPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
[1:28:57 PM] Already disconnected from Steam
```

This is with:
```
$ ./SteamPrefill --version
v1.9.1
```

Removing the "Config/account.config" file allows me to run a prefill, but doesn't save the session key.
I have manually nuked all sessions in the Steam Guard a few days ago when this first appeared.

**Comment by supra89t** [comment]
I have the same exact issue, same version. I'm running it on Unraid.

**Comment by Missanthrope85** [comment]
I am having the same issue

**Comment by tpill90** [comment]
Looks like this is not isolated to just SteamPrefill,  ArchiSteamFarm is running into the same issue as well: 
https://github.com/JustArchiNET/ArchiSteamFarm/issues/2840

Possibly related to : https://github.com/SteamRE/SteamKit/pull/1129

**Comment by Kirbo** [comment]
The same issue seems to be also at since version 1.8.4, perhaps even earlier?

**Comment by tpill90** [comment]
This issue is due to Steam changing how they handle authentication going forward,  they will no longer issue or accept "login keys".

I've played around with the changes in SteamKit2 that will handle the auth change, and have the most basic of scenarios logging in correctly.  Even though its working, I'd rather take the time and make sure that I understand the changes 100%, and to make sure I don't introduce any new bugs with these changes.  So stay tuned.

**Comment by Hornochs** [comment]
@tpill90 is already a beta out? We're hosting our LAN-Party starting tomorrow and would need some prefill 🥲

**Comment by tpill90** [comment]
> 

No beta build yet, however there is a workaround.

The current workaround is to delete the `account.config` located in the `Config` directory in between runs.  You'll still have to enter your credentials again every time, however you will still be able to run the prefill with your currently selected apps.

**Comment by tpill90** [comment]
Fix has been released in  [v2.0.0](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.0.0)

**Comment by Missanthrope85** [comment]
Thank you 😊

**Comment by DevURnd** [comment]
Working as expected, thank you for getting the fix pushed out.
