### ISSUE TITLE
Unable to load App metadata

### ISSUE THREAD

**Issue by kdog0598** [tpill90/steam-lancache-prefill#292]
**Describe the bug**
"Unable to load latest App metadata! An unexpected error occurred!
This could possibly be due to transient errors with the Steam network.
Try again in a few minutes."

I receive this error when running select-apps. I've tried multiple times over the course of 30 minutes or so, but Steam is working fine on my desktop so I think the steam network is probably fine.

**Additional Details**
 - Platform you are running SteamPrefill on:  Ubuntu 18
 - Region : US East Coast

**Log**
Contents of app.log
```
[9:45:33 AM] Starting login!
[9:45:37 AM] Connected to Steam!
[9:45:38 AM] Logged into Steam
[9:45:38 AM] Steam session initialization complete!
[9:45:59 AM] Unable to load latest App metadata! An unexpected error occurred!
[9:45:59 AM] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at SteamPrefill.Handlers.AppInfoHandler.BulkLoadAppInfosAsync(List`1 appIds)
   at SteamPrefill.Handlers.AppInfoHandler.<>c__DisplayClass7_0.<<RetrieveAppMetadataAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync(Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync(String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.AppInfoHandler.RetrieveAppMetadataAsync(List`1 appIds, Boolean loadDlcApps, Boolean loadRecentlyPlayed)
   at SteamPrefill.SteamManager.GetAllAvailableAppsAsync()
   at SteamPrefill.CliCommands.SelectAppsCommand.BuildTuiAppModelsAsync(SteamManager steamManager)
   at SteamPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)
[9:45:59 AM] Disconnected from Steam!
```

**Comment by tpill90** [comment]
I'm curious, what ended up being the issue w\ your DNS?

**Comment by kdog0598** [comment]
I'm not 100% sure, but I had an entry in dnsmasq `address=/lancache.steamcontent.com/192.168.2.38` on my pihole server that I thought had worked before, but after removing that and just setting the dns record in pihole's ui it started working fine. Doesn't make sense to me since that shouldn't have affected things other than lancache, but it started working immediately after making that change.
