### ISSUE TITLE
Unable to load latest app metadata

### ISSUE THREAD

**Issue by Cpt-Echo** [tpill90/steam-lancache-prefill#293]
When starting prefill or opening select-apps loading metadata will fail periodicly.
When metadata fails to load the application closes, stopping whatever command was attempting to be run.

Region - Australia
Platform - Docker
Discord - Cpt Echo#3755

![image](https://user-images.githubusercontent.com/7140129/235541477-8d5e7d30-b28d-42ba-b971-2bbfce6db505.png)

**Comment by Cpt-Echo** [comment]
[Metadata app.log](https://github.com/tpill90/steam-lancache-prefill/files/11369609/Metadata.app.log)
app log as requested

**Comment by themadman0980** [comment]
I am having the exact same problem, with the exact same setup: docker container (I have installed SteamPrefill inside my lancache container), living in Australia.

When I check out the SteamPrefill app.log, the following pattern is recurring:
```
[3:45:57 PM] Starting login!
[3:45:58 PM] Connected to Steam!
[3:45:58 PM] Logged into Steam
[3:45:58 PM] Steam session initialization complete!
[3:46:09 PM] Unable to load latest App metadata! An unexpected error occurred!
[3:46:09 PM] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at SteamPrefill.Handlers.AppInfoHandler.BulkLoadAppInfosAsync(List`1 appIds)
   at SteamPrefill.Handlers.AppInfoHandler.<>c__DisplayClass7_0.<<RetrieveAppMetadataAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync(Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync(String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.AppInfoHandler.RetrieveAppMetadataAsync(List`1 appIds, Boolean loadDlcApps, Boolean loadRecentlyPlayed)
   at SteamPrefill.SteamManager.GetAllAvailableAppsAsync()
   at SteamPrefill.CliCommands.SelectAppsCommand.BuildTuiAppModelsAsync(SteamManager steamManager)
   at SteamPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)```

**Comment by tpill90** [comment]
Released an initial fix in v2.1.2.  [](https://github.com/tpill90/steam-lancache-prefill/releases/tag/v2.1.2)

**Comment by codefaux** [comment]
Haven't been able to use this in a month or so -- any updates?

**Comment by Cpt-Echo** [comment]
> Haven't been able to use this in a month or so -- any updates?

Have you updated to latest build? This is partialy fixed in latest build so i now rarely see this issue anymore (maybe once a week) when it use to be 9/10 times it would error out. Tpill90 has been troubleshooting it on discord with me if you want to join the conversation.

**Comment by codefaux** [comment]
> > Haven't been able to use this in a month or so -- any updates?
> 
> Have you updated to latest build? This is partialy fixed in latest build so i now rarely see this issue anymore (maybe once a week) when it use to be 9/10 times it would error out. Tpill90 has been troubleshooting it on discord with me if you want to join the conversation.

I tried six or so times today across a few hours since it was on my mind, wasn't able to get to `select-apps` menu. Didn't try `prefill` today because I wasn't really thinking about it lol.

I'm running the Docker version via alias over ssh, doing manual pull on the image before every run, using `--rm` on the container so it should be fresh `latest` image every time, I'm not sure which software version that amounts to ie wether the container is up to date. I'll check when I'm seated next. I'm more than capable of running it directly on whatever platform, though, if that's easier for troubleshooting. Not at the computer tonight but I'm more than happy to help troubleshoot any time I'm conscious and at the desk. How do I find you?

**Comment by tpill90** [comment]
@codefaux  You can find us in the Lancache Discord server, under `#steam-prefill`. There's a link to the discord on my repo, as well on the Lancache docs.

**Comment by tpill90** [comment]
Closing this since I haven't heard of any more issues with loading the metadata. Feel free to reopen if the problem comes back

**Comment by codefaux** [comment]
Sorry, I had a significant life event occur. I forgot all about this. It seems to be working fine now, thank you for your hard work.

**Comment by nutterthanos** [comment]
error has returned
