### ISSUE TITLE
Can't login to stores for Select-Apps (Steam & Epic)

### ISSUE THREAD

**Issue by Watever44** [tpill90/steam-lancache-prefill#332]
I am trying to change my selected apps for prefill. When I go to the console, I get this error with Steam and with Epic.

**Additional Details**
 - Platform you are running SteamPrefill on: Ich777's Unraid App
 - Discord Username (if you are part of the Lancache Discord Server) : don't know how discord works (too old probably lol)
 - Region : Canada East Coast

This is the error I get on steam and Epic Select-Apps

```
prefill@04f6e9938dca:~/SteamPrefill$ ./SteamPrefill select-apps
[9:13:20 PM] Starting login!

[9:13:51 PM] Already disconnected from Steam
SteamPrefill.Models.Exceptions.SteamConnectionException: Timeout connecting to Steam...  Try again in a few moments
  at void SteamPrefill.Handlers.Steam.Steam3Session.ConnectToSteam()                                                                                                   
  at void SteamPrefill.Handlers.Steam.Steam3Session.<>c__DisplayClass16_0.<<LoginToSteamAsync>b__0>d.MoveNext()                                                        
  at void Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Status.cs:79                                                                  
  at void Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Status.cs:120                                                               
  at void Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in Progress.cs:133                                                           
  at async Task<T> Spectre.Console.Internal.DefaultExclusivityMode.RunAsync<T>(Func<Task<T>> func) in DefaultExclusivityMode.cs:40                                     
  at async Task<T> Spectre.Console.Progress.StartAsync<T>(Func<ProgressContext, Task<T>> action) in Progress.cs:116                                                    
  at async Task<T> Spectre.Console.Status.StartAsync<T>(string status, Func<StatusContext, Task<T>> func) in Status.cs:117                                             
  at async Task Spectre.Console.Status.StartAsync(string status, Func<StatusContext, Task> action) in Status.cs:77                                                     
  at async Task SteamPrefill.Handlers.Steam.Steam3Session.LoginToSteamAsync()                                                                                          
  at async Task SteamPrefill.SteamManager.InitializeAsync()                                                                                                            
  at async ValueTask SteamPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console)                                                                         
  at async ValueTask<int> CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in CliApplication.cs:148                       
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string> commandLineArguments, IReadOnlyDictionary<string, string> environmentVariables) in       
     CliApplication.cs:190                                                                                                                                             
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string> commandLineArguments) in CliApplication.cs:202                                           
  at async Task<int> SteamPrefill.Program.Main()
```

Same with Epic

```
prefill@04f6e9938dca:~/EpicPrefill$ ./EpicPrefill select-apps
[9:12:56 PM] Auth token expired.  Requesting refresh auth token...
System.Net.Http.HttpRequestException: Resource temporarily unavailable (account-public-service-prod03.ol.epicgames.com:443)
     System.Net.Sockets.SocketException: Resource temporarily unavailable                                                                                              
       at void System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError , CancellationToken )                                                
       at void System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(short )                               
       at async ValueTask System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs , ValueTask , CancellationToken
          )                                                                                                                                                            
       at async ValueTask<ValueTuple<Socket, Stream>> System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(string , int , HttpRequestMessage , bool ,              
          CancellationToken )                                                                                                                                          
  at async ValueTask<ValueTuple<Socket, Stream>> System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(string , int , HttpRequestMessage , bool , CancellationToken 
     )                                                                                                                                                                 
  at async ValueTask<ValueTuple<Socket, Stream, TransportContext>> System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , bool , CancellationToken )     
  at async ValueTask<HttpConnection> System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , bool , CancellationToken )                    
  at async Task System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )                                                                       
  at async ValueTask<T> System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )                                    
  at async ValueTask<HttpConnection> System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , bool , CancellationToken )                       
  at async ValueTask<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , bool , bool , CancellationToken
     )                                                                                                                                                                 
  at async ValueTask<HttpResponseMessage> System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , bool , CancellationToken )                                    
  at async Task<HttpResponseMessage> System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , bool ,   
     CancellationTokenSource , CancellationToken )                                                                                                                     
  at async Task EpicPrefill.Handlers.UserAccountManager.LoginAsync()                                                                                                   
  at async Task EpicPrefill.EpicGamesManager.InitializeAsync()                                                                                                         
  at async ValueTask EpicPrefill.CliCommands.SelectAppsCommand.ExecuteAsync(IConsole console) 
```

It did work in the past, but I got the same problem at some point and then it worked. May be it's the connection to the server, but would be strange to be on both, as I am able to connect on my computers to steam and epic without issues.

I have tried different things now to make it work with no success.
Disable my adguardhome dns. Remove my dns rewrite, stop the lancache dns dockers, etc...
Remove my SteamGuard, etc....
With no luck....

Any idea what it could be or how I could fix that ?

**Comment by tpill90** [comment]
Where are you running the prefills when you are running into this issue?  Is it inside the container itself on the cache host?  Have you tried running the prefills from another machine, like a client Windows machine for example?

**Comment by Watever44** [comment]
I have not tried to run it elsewhere than the container console.
I don't even know how to do it.

**Comment by tpill90** [comment]
The main instructions on how to use the app will be on the main readme for the project. 

You can also find the instructions for installing the windows version here : https://tpill90.github.io/steam-lancache-prefill/install-guides/Windows-Setup-Guide/

**Comment by Watever44** [comment]
I tried it in Windows and it worked right away. No issue in loggin and asking for password and geting a steamguard warning.
It was quick and easy. Not like in my unraid container where now it doesn't work, but even in the past it was difficult to get a steam connection. Wonder what it could be.

**Comment by tpill90** [comment]
@Watever44 Is this still a recurring issue for you?

**Comment by Watever44** [comment]
> @Watever44 Is this still a recurring issue for you?

Yes, but I am using windows has suggested to di it instead of inside the container.

**Comment by tpill90** [comment]
It sounds to me like your issue is probably due to some configuration issue with either your unRAID server, your network, or both.  What makes me think this is that the windows version continues to work as expected, but running on unRAID doesn't. 

You might want to try asking around the unRAID forums for some ideas, ich777's support thread might be a good place to start

**Comment by Patrick762** [comment]
I don't know if this helps, but it seems like in unraid you need to set a static ip for the br0. It helped me at least

**Comment by Watever44** [comment]
My ip on all my server apps are statics.

**Comment by TheRealTsevenXD** [comment]
Anyone found af fix for this?

**Comment by Goeste** [comment]
I got the same issue here on unRAID, but also the latest Win version does not work:
![image](https://github.com/user-attachments/assets/b1785678-352f-4c18-90ae-bb8fd83380b1)
Epic and Battlenet are working fine on unRAID.

**Comment by Edwin-Dijk** [comment]
> I got the same issue here on unRAID, but also the latest Win version does not work: ![image](https://private-user-images.githubusercontent.com/320889/363586095-b1785678-352f-4c18-90ae-bb8fd83380b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjc2NzAsIm5iZiI6MTcyNjIyNzM3MCwicGF0aCI6Ii8zMjA4ODkvMzYzNTg2MDk1LWIxNzg1Njc4LTM1MmYtNGMxOC05MGFlLWJiOGZkODMzODBiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxMTM2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjRlMWRhOTM0YTkzMjE2NWE4YmE4NGFkZmZiMjUxM2U3MDQ5ZDUwNWJkNjNlMjY2OTNkOGY3Y2ZmZmE3MWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aYyemHbxgjrV0wnul_N0SUGnruKDHLmcZGltZ-UlPUQ)
> 
> Log:
> 
> ```
>    at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 148
>    at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 190
>    at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 202
>    at SteamPrefill.Program.Main()
> [8:51:04 AM] Starting login!
> [8:51:09 AM] Connecting with CellId: 0
> [8:51:52 AM] Already disconnected from Steam
> [8:51:52 AM] SteamPrefill.Models.Exceptions.SteamConnectionException: Timeout connecting to Steam...  Try again in a few moments
>    at SteamPrefill.Handlers.Steam.Steam3Session.ConnectToSteam()
>    at SteamPrefill.Handlers.Steam.Steam3Session.<>c__DisplayClass16_0.<<LoginToSteamAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 79
> --- End of stack trace from previous location ---
>    at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 120
> --- End of stack trace from previous location ---
>    at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Progress\Progress.cs:line 133
> --- End of stack trace from previous location ---
>    at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
>    at Spectre.Console.Progress.StartAsync(Func`2 action) in Spectre.Console\Live\Progress\Progress.cs:line 116
>    at Spectre.Console.Status.StartAsync(String status, Func`2 func) in Spectre.Console\Live\Status\Status.cs:line 117
>    at Spectre.Console.Status.StartAsync(String status, Func`2 action) in Spectre.Console\Live\Status\Status.cs:line 77
>    at SteamPrefill.Handlers.Steam.Steam3Session.LoginToSteamAsync()
>    at SteamPrefill.SteamManager.InitializeAsync()
>    at SteamPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
>    at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 148
>    at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 190
>    at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 202
>    at SteamPrefill.Program.Main()
> ```
> 
> seems like the path really does not exyist, since my user is completly different that what is shown in the logs.. "\Users\Tim..." I am not user "Tim" aka @tpill90 ;)
> 
> Epic and Battlenet are working fine on unRAID.

This path is just for the code files, where the code was originally compiled so that most likely is not the issue here. What region are you from? At the time of your comment the latest release had bugfixes for some regions, perhaps that's why also your windows build is failing, please try again with the latest prefill?

**Comment by Goeste** [comment]
> > I got the same issue here on unRAID, but also the latest Win version does not work: ![image](https://private-user-images.githubusercontent.com/320889/363586095-b1785678-352f-4c18-90ae-bb8fd83380b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjc2NzAsIm5iZiI6MTcyNjIyNzM3MCwicGF0aCI6Ii8zMjA4ODkvMzYzNTg2MDk1LWIxNzg1Njc4LTM1MmYtNGMxOC05MGFlLWJiOGZkODMzODBiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxMTM2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjRlMWRhOTM0YTkzMjE2NWE4YmE4NGFkZmZiMjUxM2U3MDQ5ZDUwNWJkNjNlMjY2OTNkOGY3Y2ZmZmE3MWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aYyemHbxgjrV0wnul_N0SUGnruKDHLmcZGltZ-UlPUQ)
> > Log:
> > ```
> >    at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 148
> >    at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 190
> >    at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 202
> >    at SteamPrefill.Program.Main()
> > [8:51:04 AM] Starting login!
> > [8:51:09 AM] Connecting with CellId: 0
> > [8:51:52 AM] Already disconnected from Steam
> > [8:51:52 AM] SteamPrefill.Models.Exceptions.SteamConnectionException: Timeout connecting to Steam...  Try again in a few moments
> >    at SteamPrefill.Handlers.Steam.Steam3Session.ConnectToSteam()
> >    at SteamPrefill.Handlers.Steam.Steam3Session.<>c__DisplayClass16_0.<<LoginToSteamAsync>b__0>d.MoveNext()
> > --- End of stack trace from previous location ---
> >    at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 79
> > --- End of stack trace from previous location ---
> >    at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Status\Status.cs:line 120
> > --- End of stack trace from previous location ---
> >    at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in Spectre.Console\Live\Progress\Progress.cs:line 133
> > --- End of stack trace from previous location ---
> >    at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
> >    at Spectre.Console.Progress.StartAsync(Func`2 action) in Spectre.Console\Live\Progress\Progress.cs:line 116
> >    at Spectre.Console.Status.StartAsync(String status, Func`2 func) in Spectre.Console\Live\Status\Status.cs:line 117
> >    at Spectre.Console.Status.StartAsync(String status, Func`2 action) in Spectre.Console\Live\Status\Status.cs:line 77
> >    at SteamPrefill.Handlers.Steam.Steam3Session.LoginToSteamAsync()
> >    at SteamPrefill.SteamManager.InitializeAsync()
> >    at SteamPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
> >    at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 148
> >    at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 190
> >    at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 202
> >    at SteamPrefill.Program.Main()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > seems like the path really does not exyist, since my user is completly different that what is shown in the logs.. "\Users\Tim..." I am not user "Tim" aka @tpill90 ;)
> > Epic and Battlenet are working fine on unRAID.
> 
> This path is just for the code files, where the code was originally compiled so that most likely is not the issue here. What region are you from? At the time of your comment the latest release had bugfixes for some regions, perhaps that's why also your windows build is failing, please try again with the latest prefill?

you are right... everything is now working fine again :)

Thank you for the explenation

**Comment by tpill90** [comment]
I'm going to close this out as it looks like this is a bit of a grab bag of various issues now.  For anyone that is still running into problems please feel free to open another issue and we can take a look at it.
