### ISSUE TITLE
An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests

### ISSUE THREAD

**Issue by dwhmofly** [tpill90/steam-lancache-prefill#342]
This error will occur regardless of running prefill on my NAS or PC, but I can download games on steam normally on the same PC. I don't know how to solve this problem.
here is some logs

[9:15:20 PM] Starting login!
[9:15:28 PM] Connecting with CellId: 197
[9:15:30 PM] Connected to Steam!
[9:15:30 PM] Requesting new access token...
[9:15:37 PM] Logged into Steam
[9:15:39 PM] Using CM 103.28.54.171 - Singapore - Singapore
[9:15:39 PM] Loaded account licenses                                  00.3063
[9:15:39 PM] Steam session initialization complete!                   19.0198
[9:15:40 PM] Loaded metadata for 584 apps                             00.7406
[9:15:52 PM] Selected 1 apps to prefill!  
[9:15:53 PM] Loaded metadata for 0 apps                               00.0001
[9:15:53 PM] Loaded metadata for 0 apps                               00.0000
[9:15:53 PM] Starting Apex Legends
[9:15:53 PM] Requesting available CDNs. Pool currently has 0 servers available, below the desired count of 5
[9:15:56 PM] Downloading manifests for 5 depots
[9:15:56 PM] Downloading manifest 8124929965194586177 for depot 228983
[9:15:57 PM] Using CDN dl.steam.clngaa.com
[9:15:58 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[9:15:58 PM] An exception occurred while downloading manifests
[9:15:58 PM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DoRawCommandAsync(Server server, String command, Server proxyServer)
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[9:15:58 PM] Downloading manifest 8124929965194586177 for depot 228983
[9:15:59 PM] Using CDN st.dl.eccdnx.com
[9:15:59 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[9:15:59 PM] An exception occurred while downloading manifests
[9:15:59 PM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DoRawCommandAsync(Server server, String command, Server proxyServer)
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[9:16:00 PM] Downloading manifest 8124929965194586177 for depot 228983
[9:16:00 PM] Using CDN xz.pphimalayanrt.com
[9:16:00 PM]    An unexpected error (SteamKit2.SteamKitWebRequestException) occurred while downloading manifests.  Retrying...
[9:16:00 PM] An exception occurred while downloading manifests
[9:16:00 PM] SteamKit2.SteamKitWebRequestException: Response status code does not indicate success: 403 (Forbidden).
   at SteamKit2.CDN.Client.DoRawCommandAsync(Server server, String command, Server proxyServer)
   at SteamKit2.CDN.Client.DownloadManifestAsync(UInt32 depotId, UInt64 manifestId, UInt64 manifestRequestCode, Server server, Byte depotKey, Server proxyServer)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
[9:16:02 PM] Unexpected download error : Unable to download manifests!  Skipping app...
[9:16:02 PM] SteamPrefill.Models.Exceptions.ManifestException: Unable to download manifests!
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)
   at SteamPrefill.Handlers.DepotHandler.BuildChunkDownloadQueueAsync(List`1 depots)
   at SteamPrefill.SteamManager.<>c__DisplayClass13_0.<<DownloadSingleAppAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync(Func`1 func) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync(Func`2 action) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync(String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.SteamManager.DownloadSingleAppAsync(UInt32 appId)
   at SteamPrefill.SteamManager.DownloadMultipleAppsAsync(Boolean downloadAllOwnedGames, Boolean prefillRecentGames, Nullable`1 prefillPopularGames)
[9:16:02 PM] Prefill complete!
[9:16:02 PM] Disconnected from Steam!

**Comment by tpill90** [comment]
Are you still having this issue?

**Comment by tpill90** [comment]
Closing since there has been no additional info

**Comment by sgpublic** [comment]
I also encountered this problem, here is the log:
 
```
[8:09:59 AM] Starting login!
Connecting to Steam...
[8:10:02 AM] Connected to Steam!
Logging in to Steam...
[8:10:03 AM] Logged into Steam
Retrieving owned apps...
[8:10:05 AM] Loaded account licenses                             00.9352
[8:10:05 AM] Steam session initialization complete!              05.7734
────────────────────────────────────────────────────────────────────────────────
Retrieving latest App metadata...
[8:10:09 AM] Starting Apex Legends
 Getting available CDN Servers... 
 Getting available CDN Servers...  Retrying 1
 Getting available CDN Servers...  Retrying 2
 Getting available CDN Servers...  Retrying 3
Fetching depot manifests...
[8:10:15 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:16 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:18 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:20 AM] Unexpected download error : Unable to download manifests!  Skipping
app...
[8:10:20 AM] Starting DEAD OR ALIVE Xtreme Venus Vacation
 Getting available CDN Servers... 
 Getting available CDN Servers...  Retrying 1
 Getting available CDN Servers...  Retrying 2
 Getting available CDN Servers...  Retrying 3
Fetching depot manifests...
[8:10:25 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:27 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:29 AM]    An unexpected error (SteamKit2.SteamKitWebRequestException) 
occurred while downloading manifests.  Retrying...
[8:10:30 AM] Unexpected download error : Unable to download manifests!  Skipping
app...
...
```

docker-compose.yaml:

```yaml
version: "3"
services:
  example:
    image: tpill90/steam-lancache-prefill:v2.6.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/core/app/steam-lancache-prefill:/Config
    entrypoint: ["/SteamPrefill", "prefill"]
    # entrypoint: ["sleep", "10000"]
```

I use a transparent proxy on my network, so in theory it should be possible to download Steam content, and it is.
