### ISSUE TITLE
LancachePrefill.Common.Exceptions.LancacheNotFoundException

### ISSUE THREAD

**Issue by michaelkr1** [tpill90/steam-lancache-prefill#359]
**Describe the bug**
```
[1:48:04 AM] LancachePrefill.Common.Exceptions.LancacheNotFoundException: No Lancache server detected at 192.168.100.67
   at LancachePrefill.Common.LancacheIpResolver.IsLancacheServerRunningAsync(String cdnUrl)
   at LancachePrefill.Common.LancacheIpResolver.ResolveLancacheIpAsync(IAnsiConsole ansiConsole, String cdnUrl)
   at SteamPrefill.Handlers.DownloadHandler.InitializeAsync()
   at SteamPrefill.Handlers.DownloadHandler.DownloadQueuedChunksAsync(List`1 queuedRequests, DownloadArguments downloadArgs)
   at SteamPrefill.SteamManager.DownloadSingleAppAsync(UInt32 appId)
   at SteamPrefill.SteamManager.DownloadMultipleAppsAsync(Boolean downloadAllOwnedGames, Boolean prefillRecentGames, Nullable`1 prefillPopularGames)
   at SteamPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
   at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 148
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 190
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 202
   at SteamPrefill.Program.Main()
```

My LanCache is working as expected on 192.168.100.67 and I have tested it by downloading games via Steam, uninstalling them, and re-downloading and can see it hitting the Cache. However Prefill doesn't believe my Lancache is running and throws the above error from the app.log. See screenshot below from running prefill cmd. Also attached is a screenshot of a curl to the lancache-heartbeat showing the ` X-LanCache-Processed-By` response.

**Additional Details**
 - Platform you are running SteamPrefill on: Ich777's Unraid App
 - Discord Username (if you are part of the Lancache Discord Server) : n/a

**Screenshots**
![Screenshot 2024-02-16 020146](https://github.com/tpill90/steam-lancache-prefill/assets/2259973/60e9f572-88c5-4f5d-b048-5ea27c4f1b7d)

![Screenshot 2024-02-16 020420](https://github.com/tpill90/steam-lancache-prefill/assets/2259973/931a1ee1-452d-4380-b429-798c014014ec)

**Comment by michaelkr1** [comment]
This is resolved. It was a configuration error on my behalf.
My docker containers run using an ipvlan network and my prefill container was running using host networking and not with an assigned IP on the ipvlan network.
