### ISSUE TITLE
Fails to use lancache server behind nginx proxy, despite steam actively using it

### ISSUE THREAD

**Issue by sugoidogo** [tpill90/steam-lancache-prefill#384]
**Describe the bug**
Getting error "Unable to detect Lancache server!", but steam client on PC detects and uses it

**Additional Details**
Host OS is Fedora 40. Tried running on Docker(podman) as well as downloading the binary and running it on bare metal, same result.

**Logs**
app.log:
```
[7:56:57 AM] Starting login!
[7:56:57 AM] Connecting with CellId: 64
[7:56:58 AM] Connected to Steam!
[7:56:59 AM] Logged into Steam
[7:56:59 AM] Connected to CM Unspecified/ext1-lax1.steamserver.net:27035
[7:56:59 AM] Loaded account licenses                                  00.2406
[7:56:59 AM] Steam session initialization complete!                   01.7725
[7:56:59 AM] Loaded metadata for 8 apps                               00.4645
[7:57:00 AM] Loaded metadata for 11 apps                              00.2470
[7:57:00 AM] Starting Call of Duty®
[7:57:00 AM] Requesting available CDNs. Pool currently has 0 servers available, below the desired count of 5
[7:57:00 AM] Downloading manifests for 14 depots
[7:57:00 AM] Downloading 93.98 GiB from 115730 chunks
[7:57:01 AM] Disconnected from Steam!
[7:57:01 AM] LancachePrefill.Common.Exceptions.LancacheNotFoundException: Unable to detect Lancache server!
   at LancachePrefill.Common.LancacheIpResolver.ResolveLancacheIpAsync(IAnsiConsole ansiConsole, String cdnUrl)
   at SteamPrefill.Handlers.DownloadHandler.InitializeAsync()
   at SteamPrefill.Handlers.DownloadHandler.DownloadQueuedChunksAsync(List`1 queuedRequests, DownloadArguments downloadArgs)
   at SteamPrefill.SteamManager.DownloadSingleAppAsync(UInt32 appId)
   at SteamPrefill.SteamManager.DownloadMultipleAppsAsync(Boolean downloadAllOwnedGames, Boolean prefillRecentGames, Nullable`1 prefillPopularGames)
   at SteamPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
   at CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 148
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments, IReadOnlyDictionary`2 environmentVariables) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 190
   at CliFx.CliApplication.RunAsync(IReadOnlyList`1 commandLineArguments) in C:\Users\Tim\Dropbox\Programming\Lancache-Prefills\External\CliFx\CliFx\CliApplication.cs:line 202
   at SteamPrefill.Program.Main()
```
Command lines used:
```
root@sugoiserver:/opt/lancache-prefill# nslookup lancache.steamcontent.com
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   lancache.steamcontent.com
Address: 10.10.10.230
```
```
root@sugoiserver:/opt/lancache-prefill# ./SteamPrefill prefill
[7:44:09 AM] Starting login!
[7:44:10 AM] Connected to Steam!
[7:44:10 AM] Logged into Steam
[7:44:11 AM] Loaded account licenses                             00.2737
[7:44:11 AM] Steam session initialization complete!              02.0028

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

[7:44:12 AM] Starting Call of Duty®
[7:44:12 AM] Disconnected from Steam!
LancachePrefill.Common.Exceptions.LancacheNotFoundException: Unable to detect Lancache server!
  at async Task<string> LancachePrefill.Common.LancacheIpResolver.ResolveLancacheIpAsync(IAnsiConsole ansiConsole, string cdnUrl)
  at async Task SteamPrefill.Handlers.DownloadHandler.InitializeAsync()
  at async Task<bool> SteamPrefill.Handlers.DownloadHandler.DownloadQueuedChunksAsync(List<QueuedRequest> queuedRequests, DownloadArguments downloadArgs)
  at async Task SteamPrefill.SteamManager.DownloadSingleAppAsync(uint appId)
  at async Task SteamPrefill.SteamManager.DownloadMultipleAppsAsync(bool downloadAllOwnedGames, bool prefillRecentGames, int? prefillPopularGames)
  at async ValueTask SteamPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
  at async ValueTask<int> CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in CliApplication.cs:148
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string> commandLineArguments, IReadOnlyDictionary<string, string> environmentVariables) in CliApplication.cs:190
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string> commandLineArguments) in CliApplication.cs:202
  at async Task<int> SteamPrefill.Program.Main()
```
```
root@sugoiserver:/opt/lancache-prefill# docker run -it --rm --net=host --volume ./Config:/Config tpill90/steam-lancache-prefill:latest prefill
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
[2:45:01 PM] Starting login!
[2:45:02 PM] Connected to Steam!
[2:45:03 PM] Logged into Steam
[2:45:03 PM] Loaded account licenses                             00.3608
[2:45:03 PM] Steam session initialization complete!              01.8720

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

[2:45:04 PM] Starting Call of Duty®
[2:45:23 PM] Disconnected from Steam!
LancachePrefill.Common.Exceptions.LancacheNotFoundException: Unable to detect Lancache server!
  at async Task<string> LancachePrefill.Common.LancacheIpResolver.ResolveLancacheIpAsync(IAnsiConsole ansiConsole, string cdnUrl)
  at async Task SteamPrefill.Handlers.DownloadHandler.InitializeAsync()
  at async Task<bool> SteamPrefill.Handlers.DownloadHandler.DownloadQueuedChunksAsync(List<QueuedRequest> queuedRequests, DownloadArguments downloadArgs)
  at async Task SteamPrefill.SteamManager.DownloadSingleAppAsync(uint appId)
  at async Task SteamPrefill.SteamManager.DownloadMultipleAppsAsync(bool downloadAllOwnedGames, bool prefillRecentGames, int? prefillPopularGames)
  at async ValueTask SteamPrefill.CliCommands.PrefillCommand.ExecuteAsync(IConsole console)
  at async ValueTask<int> CliFx.CliApplication.RunAsync(ApplicationSchema applicationSchema, CommandInput commandInput) in CliApplication.cs:148
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string> commandLineArguments, IReadOnlyDictionary<string, string> environmentVariables) in CliApplication.cs:190
  at async ValueTask<int> CliFx.CliApplication.RunAsync(IReadOnlyList<string> commandLineArguments) in CliApplication.cs:202
  at async Task<int> SteamPrefill.Program.Main()
```

**Comment by sugoidogo** [comment]
Tried using a hosts file entry to set the lancache address to localhost since I'm running this on the same machine as lancache, got a different error: "Sequence contains no matching element"
```
root@sugoiserver:/opt/lancache-prefill# ./SteamPrefill prefill
[8:58:15 AM] Starting login!
[8:58:17 AM] Connected to Steam!
[8:58:17 AM] Logged into Steam
[8:58:18 AM] Loaded account licenses                             00.2484
[8:58:18 AM] Steam session initialization complete!              02.0715

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

[8:58:18 AM] Starting Call of Duty®
[8:58:19 AM] Unexpected download error : Sequence contains no matching element  Skipping app...

[8:58:19 AM] Starting DEATH STRANDING DIRECTOR'S CUT
[8:58:22 AM] Unexpected download error : Sequence contains no matching element  Skipping app...

[8:58:22 AM] Starting FINAL FANTASY XVI
[8:58:25 AM] Unexpected download error : Sequence contains no matching element  Skipping app...

[8:58:25 AM] Starting Forza Horizon 4
[8:58:27 AM] Unexpected download error : Sequence contains no matching element  Skipping app...

[8:58:27 AM] Starting Forza Horizon 5
[8:58:29 AM] Unexpected download error : Sequence contains no matching element  Skipping app...

[8:58:29 AM] Starting God of War Ragnarök
[8:58:31 AM] Unexpected download error : Sequence contains no matching element  Skipping app...

[8:58:31 AM] Starting Horizon Forbidden West™ Complete Edition
[8:58:34 AM] Unexpected download error : Sequence contains no matching element  Skipping app...

[8:58:34 AM] Starting Mass Effect™ Legendary Edition
[8:58:38 AM] Unexpected download error : Sequence contains no matching element  Skipping app...

[8:58:38 AM] Prefill complete!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Prefilled 8 apps totaling 798.89 GiB in 22.3954

   Updated │ Up To Date │ Failed
  ━━━━━━━━━┿━━━━━━━━━━━━┿━━━━━━━━
      0    │     0      │   8

[8:58:38 AM] Disconnected from Steam!
```

**Comment by sugoidogo** [comment]
Fixed by moving lancache-monolithic container to another machine in host networking mode instead of behind nginx-proxy-manager. My setup makes this very inefficient since my mass storage is on the same machine that needs to run nginx-proxy-manager on port 80. The steam client has no issue using lancache in this setup, I would appreciate it if this issue could be fixed so that I can move my processes back to my file server.

**Comment by tpill90** [comment]
The reason you're likely running into this issue is because your additional nginx proxy that you're running everything through is stripping headers that SteamPrefill is expecting to be there.  SteamPrefill specifically looks for the `X-LanCache-Processed-By` header to confirm that there is a Lancache instance running at the private IP that `lancache.steamcontent.com` is resolving to.  Steam is working because it doesn't do any of these checks.  These checks were added to have some diagnostics around common Lancache configuration mistakes, because otherwise Steam would just silently not work without any indication that it isn't finding the Lancache.

Try putting your configuration back to how you had it originally, and configure your extra nginx instance to pass those headers through, and see if it fixes your issue.
