### ISSUE TITLE
Unable to download "Sid Meier's Civilization VI"

### ISSUE THREAD

**Issue by stuart-c-moore** [tpill90/steam-lancache-prefill#83]
_Originally posted by @stuart-c-moore in https://github.com/tpill90/steam-lancache-prefill/issues/70#issuecomment-1221117632_

Here is the error log:

```
stuart@lancache:~/SteamPrefill-1.3.0-linux-x64$ cat errorlog.txt
[[10:48:40 PM]] An exception occurred while downloading manifests[[10:48:40 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1523210 1523211 4005512837758401031
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[10:48:44 PM]] An exception occurred while downloading manifests[[10:48:44 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1523210 1523211 4005512837758401031
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
   at SteamPrefill.Handlers.ManifestHandler.GetAllManifestsAsync(List`1 depots)[[10:48:52 PM]] An exception occurred while downloading manifests[[10:48:52 PM]] SteamPrefill.Models.Exceptions.ManifestException: No manifest request code was returned for 1523210 1523211 4005512837758401031
   at SteamPrefill.Handlers.ManifestHandler.GetManifestRequestCodeAsync(DepotInfo depot)
   at SteamPrefill.Handlers.ManifestHandler.GetSingleManifestAsync(DepotInfo depot, Server server)
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_1.<<AttemptManifestDownloadAsync>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at SteamPrefill.Handlers.ManifestHandler.<>c__DisplayClass6_0.<<AttemptManifestDownloadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Internal\DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Progress\Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in C:\Users\Tim\Dropbox\Programming\dotnet-public\spectre.console\src\Spectre.Console\Live\Status\Status.cs:line 77
   at SteamPrefill.Handlers.ManifestHandler.AttemptManifestDownloadAsync(List`1 depots)
```

**Comment by tpill90** [comment]
[SteamPrefill-1.3.1-linux-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9387621/SteamPrefill-1.3.1-linux-x64.zip)
[SteamPrefill-1.3.1-win-x64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9387622/SteamPrefill-1.3.1-win-x64.zip)
[SteamPrefill-1.3.1-linux-arm64.zip](https://github.com/tpill90/steam-lancache-prefill/files/9387623/SteamPrefill-1.3.1-linux-arm64.zip)
